@echo off
setlocal ENABLEDELAYEDEXPANSION
for /f "usebackq" %%a in (`type testSend\user_hash.txt`) do set user_hash=%%a
set sales_id=100
set item_id=203866
set query_string=ATMEGA16-16AU

if "%1" == "" (
    set n=1
) else (
    set n=%1
)

for /l %%a in (1,1,%n%) do (
    call :tests
    ping -n 10 127.0.0.1 > nul
)
goto :eof

:tests
REM testSend purgeQueue timestamp "{'user_hash': '%user_hash%'}"

testSend delivery_prognosis "{'user_hash': '%user_hash%', 'item_id': '%item_id%'}"
testSend item_info "{'user_hash': '%user_hash%', 'item_id': '%item_id%'}"
testSend multiplicate_values "{'user_hash': '%user_hash%', 'value1': '10', 'value2': '14'}"
testSend quotation_handle_header "{'user_hash': '%user_hash%'}"
testSend sales_delivery "{'user_hash': '%user_hash%', 'sales_id': '%sales_id%'}"
testSend sales_handle_edit "{'user_hash': '%user_hash%', 'sales_id': '%sales_id%'}"
testSend search_item_name_dms_h "{'user_hash': '%user_hash%', 'query_string': '%query_string%'}"
testSend search_item_name_h "{'user_hash': '%user_hash%', 'query_string': '%query_string%'}"
testSend add_dlv_mode "{'user_hash': '%user_hash%'}"
testSend address_add "{'user_hash': '%user_hash%'}"
testSend application_area_list "{'user_hash': '%user_hash%'}"
testSend auto_process_quotation "{'user_hash': '%user_hash%'}"
testSend calc_dlv_amount "{'user_hash': '%user_hash%'}"
testSend claim_create "{'user_hash': '%user_hash%'}"
testSend claim_info "{'user_hash': '%user_hash%'}"
testSend confirm_payment "{'user_hash': '%user_hash%'}"
testSend contact_add "{'user_hash': '%user_hash%', 'last_name': 'asdf', 'first_name': 'asdf', 'phone': '8987654321'}"
testSend contact_edit "{'user_hash': '%user_hash%', 'contact_id': 'asdf'}"
testSend contact_list "{'user_hash': '%user_hash%'}"
testSend create_invoice "{'user_hash': '%user_hash%'}"
:: testSend create_quotation "{'user_hash': '%user_hash%'}"
:: testSend cust_list_offline "{'user_hash': '%user_hash%'}"
:: testSend cust_types "{'user_hash': '%user_hash%'}"
:: testSend dat_inventory_create_jour "{'user_hash': '%user_hash%', 'keyword': 'aaa'}"
:: testSend dat_inventory_item "{'user_hash': '%user_hash%', 'keyword': 'aaa'}"
:: testSend dat_inventory_post_jour "{'user_hash': '%user_hash%', 'keyword': 'aaa'}"
:: testSend dat_inventory_qty "{'user_hash': '%user_hash%', 'keyword': 'aaa'}"
:: testSend dat_inventory_wmslocation "{'user_hash': '%user_hash%', 'keyword': 'aaa'}"
:: testSend dat_pallets_reset "{'user_hash': '%user_hash%', 'keyword': 'aaa'}"
:: testSend dat_pallets_scan_4accept "{'user_hash': '%user_hash%', 'keyword': 'aaa'}"
:: testSend dat_pallets_scan_arrival "{'user_hash': '%user_hash%', 'keyword': 'aaa'}"
:: testSend dat_transport_4accept "{'user_hash': '%user_hash%', 'keyword': 'aaa'}"
:: testSend dat_transport_arrival "{'user_hash': '%user_hash%', 'keyword': 'aaa'}"
:: testSend dat_transport_scan_4accept "{'user_hash': '%user_hash%', 'keyword': 'aaa'}"
:: testSend dat_transport_sort "{'user_hash': '%user_hash%', 'keyword': 'aaa'}"
:: testSend dc_option_list "{'user_hash': '%user_hash%'}"
:: testSend delivery_plan "{'user_hash': '%user_hash%'}"
:: testSend deposit_invoice "{'user_hash': '%user_hash%'}"
:: testSend deposit_link "{'user_hash': '%user_hash%'}"
:: testSend deposit_margin "{'user_hash': '%user_hash%'}"
:: testSend get_dlv_mode "{'user_hash': '%user_hash%'}"
:: testSend get_exchange_rate "{'user_hash': '%user_hash%', 'currency': 'USD'}"
:: testSend get_places "{'user_hash': '%user_hash%'}"
:: testSend info_cust "{'user_hash': '%user_hash%'}"
:: testSend info_cust_balance "{'user_hash': '%user_hash%'}"
:: testSend info_cust_contracts "{'user_hash': '%user_hash%'}"
:: testSend info_cust_limits "{'user_hash': '%user_hash%'}"
:: testSend info_cust_trans "{'user_hash': '%user_hash%'}"
:: testSend invent_class_assign "{'user_hash': '%user_hash%'}"
:: testSend inventory_active_add "{'user_hash': '%user_hash%'}"
:: testSend inventory_subst_add "{'user_hash': '%user_hash%'}"
:: testSend invoice_lines "{'user_hash': '%user_hash%'}"
:: testSend invoice_paym "{'user_hash': '%user_hash%'}"
:: testSend invoice_paym_info "{'user_hash': '%user_hash%'}"
:: testSend invoice_paym_lines "{'user_hash': '%user_hash%', 'invoice_paym': 'cvb', 'date': '2016-09-01', 'sales_id': 'qwer'}"
:: testSend isearch_list_request "{'user_hash': '%user_hash%'}"
:: testSend isearch_request "{'user_hash': '%user_hash%'}"
:: testSend items "{'user_hash': '%user_hash%'}"
:: testSend make_order "{'user_hash': '%user_hash%'}"
:: testSend make_order_ext "{'user_hash': '%user_hash%'}"
:: testSend pbf_link_paym "{'user_hash': '%user_hash%', 'currency': 'USD'}"
:: testSend pbf_sync_paym "{'user_hash': '%user_hash%', 'company': 'abc'}"
:: testSend place_info "{'user_hash': '%user_hash%'}"
:: testSend place_lines "{'user_hash': '%user_hash%'}"
:: testSend quotation_handle_header "{'user_hash': '%user_hash%'}"
:: testSend quotation_info "{'user_hash': '%user_hash%'}"
:: testSend quotation_lines "{'user_hash': '%user_hash%'}"
:: testSend quotation_to_order "{'user_hash': '%user_hash%', 'customer_delivery_type_id': 'zxcvb'}"
:: testSend quotation_unknowns "{'user_hash': '%user_hash%', 'quotation_id': 'asdf'}"
:: testSend retail_price "{'user_hash': '%user_hash%'}"
:: testSend rpay_sync_cash "{'user_hash': '%user_hash%', 'label_date': '2016-09-01', 'label_document': 'asdf', 'date': '2016-09-01', 'company_code': '000'}"
:: testSend rpay_sync_empl "{'user_hash': '%user_hash%', 'first_name': 'zcxvb'}"
:: testSend rpay_sync_paym "{'user_hash': '%user_hash%', 'label_date': '2016-06-06', 'label_document': 'asdf'}"
:: testSend rpay_sync_trans "{'user_hash': '%user_hash%', 'label_date': 'Август 2016'}"
:: testSend sales_close_reason_list "{'user_hash': '%user_hash%'}"
:: testSend sales_create_auto "{'user_hash': '%user_hash%'}"
:: testSend sales_handle_add "{'user_hash': '%user_hash%'}"
:: testSend sales_handle_add_ext "{'user_hash': '%user_hash%'}"
:: testSend sales_handle_add_new "{'user_hash': '%user_hash%'}"
:: testSend sales_handle_edit_ext "{'user_hash': '%user_hash%', 'sales_id': 'asdf'}"
:: testSend sales_handle_header "{'user_hash': '%user_hash%'}"
:: testSend sales_info "{'user_hash': '%user_hash%'}"
:: testSend sales_lines "{'user_hash': '%user_hash%'}"
:: testSend sales_report "{'user_hash': '%user_hash%'}"
:: testSend sales_status_list "{'user_hash': '%user_hash%'}"
:: testSend sales_tracking "{'user_hash': '%user_hash%'}"
:: testSend sales_transfer "{'user_hash': '%user_hash%'}"
:: testSend search_item_an_h "{'user_hash': '%user_hash%', 'item_id_search': 'asdf'}"
:: testSend search_item_ks_h "{'user_hash': '%user_hash%'}"
:: testSend search_item_name_quick "{'user_hash': '%user_hash%'}"
:: testSend timestamp "{'user_hash': '%user_hash%'}"
:: testSend tpl_assembly_request "{'user_hash': '%user_hash%'}"
:: testSend tpl_create_item "{'user_hash': '%user_hash%', 'item_name': 'asdfg'}"
:: testSend tpl_movement_request "{'user_hash': '%user_hash%', 'request_id': 'ttt'}"
:: testSend tpl_putaway_cancel "{'user_hash': '%user_hash%'}"
:: testSend tpl_putaway_report "{'user_hash': '%user_hash%'}"
:: testSend tpl_putaway_request "{'user_hash': '%user_hash%', 'location_id_from': 'zxcv'}"
:: testSend tpl_report "{'user_hash': '%user_hash%'}"
:: testSend tpl_shipping_request "{'user_hash': '%user_hash%', 'request_id': 'asdf'}"
:: testSend transport_journal "{'user_hash': '%user_hash%'}"
:: testSend user_edit "{'user_hash': '%user_hash%'}"
:: testSend user_info "{'user_hash': '%user_hash%'}"
:: testSend user_list "{'user_hash': '%user_hash%'}"
:: testSend user_list_alt "{'user_hash': '%user_hash%'}"
:: testSend user_registration "{'user_hash': '%user_hash%'}"
:: testSend vend_ordrsp "{'user_hash': '%user_hash%'}"
:: testSend vend_price_import "{'user_hash': '%user_hash%'}"
:: testSend vend_proposal_alert "{'user_hash': '%user_hash%'}"
:: testSend vend_proposal_save "{'user_hash': '%user_hash%', 'name': 'asdf'}"
:: testSend wms_transport_status "{'user_hash': '%user_hash%', 'transport_id': 'asdf', 'transport_status': 'receive'}"